source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '13.0'

target 'CocoaPodsExample_Example' do
  pod 'RheaExtension', :path => 'Modules/RheaExtension/'
  pod 'Account', :path => 'Modules/Account/'
end

# 如果在各个 podspec 中不使用 s.pod_target_xcconfig 和 s.user_target_xcconfig, 也可以在 podfile 中添加如下脚本统一处理

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    rhea_dependency = target.dependencies.find { |d| ['RheaTime', 'RheaExtension'].include?(d.name) }
#    if rhea_dependency
#      puts "Adding Rhea Swift flags to target: #{target.name}"
#      target.build_configurations.each do |config|
#        swift_flags = config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)']
#        
#        plugin_flag = '-Xfrontend -load-plugin-executable -Xfrontend ${PODS_ROOT}/RheaTime/Sources/Resources/RheaTimeMacros#RheaTimeMacros'
#        
#        unless swift_flags.join(' ').include?(plugin_flag)
#          swift_flags.concat(plugin_flag.split)
#        end
#        
#        # 添加 SymbolLinkageMarkers 实验性特性标志
#        symbol_linkage_flag = '-enable-experimental-feature SymbolLinkageMarkers'
#        
#        unless swift_flags.join(' ').include?(symbol_linkage_flag)
#          swift_flags.concat(symbol_linkage_flag.split)
#        end
#        
#        config.build_settings['OTHER_SWIFT_FLAGS'] = swift_flags
#      end
#    end
#  end
#end
